apiVersion: apps/v1
kind: Deployment
metadata:
  name: sellenix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sellenix
  template:
    metadata:
      labels:
        app: sellenix
    spec:
      containers:
      - name: sellenix
        image: $DOCKER_REGISTRY/sellenix:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: sellenix-secrets
              key: database-url
        - name: MOLLIE_API_KEY
          valueFrom:
            secretKeyRef:
              name: sellenix-secrets
              key: mollie-api-key

